creation_rules:
  - path_regex: local.env$
    age: >-
      age1lq5guvuugw57nv88px3gvcn3lc39tw4pw3tt3pfgjr76sjt3ketstg6cqm,
      age1rvsrx3qc0fz3376p69apmke0qs9jeaum7wewe7x0veaxeu2ejsxsx2qa0a
  - path_regex: remote.env$
    age: >-
      age1lq5guvuugw57nv88px3gvcn3lc39tw4pw3tt3pfgjr76sjt3ketstg6cqm,
