services:
  proxyt:
    image: "shlinkio/shlink:stable"
    volumes:
      - proxyt-certs:/certs
    command: serve --domain proxyt.thekoppe.com --cert-dir /certs --http-only
    networks:
      - cloudflared

volumes:
  proxyt-certs:

networks:
  cloudflared:
    external: true
