[[stack]]
name = "convex"
deploy = true
tags = ["syncs"]
[stack.config]
server_id = "bird"

auto_pull = true
auto_update = true
destroy_before_deploy = true

linked_repo = "komodo-syncs-bird"
run_directory = "./stacks/bird/convex"

environment = """
  CONVEX_CLOUD_ORIGIN=https://convex.thekoppe.com
  CONVEX_SITE_ORIGIN=https://convexsite.thekoppe.com
  DO_NOT_REQUIRE_SSL=true
  INSTANCE_NAME=thekoppe
"""
additional_env_files = ["./bird.env"]
